### ISSUE TITLE
[Proposal] Add support for both: before and after at the same time.

### ISSUE THREAD

**Issue by liorocks** [zgabievi/bem#6]
We have both, but we have separately:

``` sass
@include b('list') {
    @include before {
        color: black;
    }
}
```

and 

``` sass
@include b('list') {
    @include after {
        color: black;
    }
}
```

Can we create new mixin like this?

``` sass
@include b('list') {
    @include before_after {
        color: black;
    }
}
```

Or usage like this would be awesome:

``` sass
@include b('list') {
    @include before, after {
        color: black;
    }

 # or like this
  @include before,
  @include after {
     color:black;
  }
}
```

**Comment by zgabievi** [comment]
Sass have no support to use mixins separated by comma, if you want to write before and after in one mixin, you can use `parse` like this:

``` scss
@include b('list') {
    @include parse(':before', ':after') {
        color: black;
    }
}
```
